name: Release

on:
  release:
    types:
      - published

jobs:
  goreleaser:
    name: Build with goreleaser
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          check-latest: true

      - name: Generate GitHub app token
        id: github-app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: adaricorp

      - name: Configure git authentication
        run: |
          git config --global url."https://x-access-token:${{ steps.github-app-token.outputs.token }}@github.com/".insteadOf "https://github.com/"

      - name: Set build date
        run: |
          echo "BUILD_DATE=$(date)" >> ${GITHUB_ENV}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          BUILD_USER: ${{ github.actor }} (via Github Actions)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
